spring:
  # JPA 관련 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  # 데이터 소스(DB 연결) 관련 설정
  datasource:
    url: jdbc:h2:mem:testdb
    # username과 password는 기본값이 sa, '' 이므로 보통 생략 가능합니다.
    # username: sa
    # password:

  # H2 콘솔 관련 설정
  h2:
    console:
      enabled: true
      path: /h2-console  # 콘솔 접속 경로를 명시적으로 지정해주는 것이 좋습니다.